/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Ad {
  'id' : string,
  'title' : string,
  'imageUrl' : string,
  'videoUrl' : string,
  'link' : string,
}
export interface DMMessage {
  'content' : string,
  'toUser' : Principal,
  'timestamp' : Time,
  'fromUser' : Principal,
}
export type ExternalBlob = Uint8Array;
export interface FriendRequest {
  'status' : string,
  'toUser' : Principal,
  'fromUser' : Principal,
}
export interface Group {
  'members' : Array<Principal>,
  'name' : string,
  'createdBy' : Principal,
  'description' : string,
  'spawnInterval' : bigint,
}
export interface GroupMessage {
  'id' : string,
  'isWaifuSpawn' : boolean,
  'content' : string,
  'waifuCharacterId' : string,
  'senderPrincipal' : Principal,
  'timestamp' : Time,
  'senderName' : string,
  'groupName' : string,
}
export interface OwnedWaifu {
  'userId' : Principal,
  'obtainedAt' : bigint,
  'isFavorite' : boolean,
  'characterId' : string,
}
export interface ShopItem {
  'id' : string,
  'name' : string,
  'description' : string,
  'itemType' : string,
  'price' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'balance' : bigint,
  'displayName' : string,
  'joinDate' : Time,
  'profilePic' : ExternalBlob,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WaifuCharacter {
  'id' : string,
  'name' : string,
  'series' : string,
  'imageUrl' : string,
  'rarity' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptFriendRequest' : ActorMethod<[Principal], undefined>,
  'addAd' : ActorMethod<[Ad], undefined>,
  'addMemberToGroup' : ActorMethod<[string, Principal], undefined>,
  'addShopItem' : ActorMethod<[ShopItem], undefined>,
  'addWaifuCharacter' : ActorMethod<[WaifuCharacter], undefined>,
  'addWaifuToHarem' : ActorMethod<[OwnedWaifu], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createGroup' : ActorMethod<[Group], undefined>,
  'deleteAd' : ActorMethod<[string], undefined>,
  'deleteWaifuCharacter' : ActorMethod<[string], undefined>,
  'getAds' : ActorMethod<[], Array<Ad>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFriendRequests' : ActorMethod<[Principal], Array<FriendRequest>>,
  'getGroupMembers' : ActorMethod<[string], Array<Principal>>,
  'getGroupMessages' : ActorMethod<[string], Array<GroupMessage>>,
  'getGroups' : ActorMethod<[], Array<Group>>,
  'getMessagesWith' : ActorMethod<[Principal], Array<DMMessage>>,
  'getShopItems' : ActorMethod<[], Array<ShopItem>>,
  'getUserHarem' : ActorMethod<[Principal], Array<OwnedWaifu>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWaifuCharacters' : ActorMethod<[], Array<WaifuCharacter>>,
  'huntWaifuInGroup' : ActorMethod<[string], [] | [WaifuCharacter]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinGroup' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendDM' : ActorMethod<[Principal, string], undefined>,
  'sendFriendRequest' : ActorMethod<[Principal], undefined>,
  'sendGroupMessage' : ActorMethod<[string, string], undefined>,
  'transferOnex' : ActorMethod<[Principal, bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
