/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ShopItem = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'itemType' : IDL.Text,
  'price' : IDL.Nat,
});
export const WaifuCharacter = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'series' : IDL.Text,
  'imageUrl' : IDL.Text,
  'rarity' : IDL.Text,
});
export const OwnedWaifu = IDL.Record({
  'userId' : IDL.Principal,
  'obtainedAt' : IDL.Nat,
  'isFavorite' : IDL.Bool,
  'characterId' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Group = IDL.Record({
  'members' : IDL.Vec(IDL.Principal),
  'name' : IDL.Text,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'spawnInterval' : IDL.Nat,
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'balance' : IDL.Nat,
  'displayName' : IDL.Text,
  'joinDate' : Time,
  'profilePic' : ExternalBlob,
});
export const FriendRequest = IDL.Record({
  'status' : IDL.Text,
  'toUser' : IDL.Principal,
  'fromUser' : IDL.Principal,
});
export const GroupMessage = IDL.Record({
  'id' : IDL.Text,
  'isWaifuSpawn' : IDL.Bool,
  'content' : IDL.Text,
  'waifuCharacterId' : IDL.Text,
  'senderPrincipal' : IDL.Principal,
  'timestamp' : Time,
  'senderName' : IDL.Text,
  'groupName' : IDL.Text,
});
export const DMMessage = IDL.Record({
  'content' : IDL.Text,
  'toUser' : IDL.Principal,
  'timestamp' : Time,
  'fromUser' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptFriendRequest' : IDL.Func([IDL.Principal], [], []),
  'addMemberToGroup' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'addShopItem' : IDL.Func([ShopItem], [], []),
  'addWaifuCharacter' : IDL.Func([WaifuCharacter], [], []),
  'addWaifuToHarem' : IDL.Func([OwnedWaifu], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGroup' : IDL.Func([Group], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFriendRequests' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(FriendRequest)],
      ['query'],
    ),
  'getGroupMembers' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Principal)], ['query']),
  'getGroupMessages' : IDL.Func([IDL.Text], [IDL.Vec(GroupMessage)], ['query']),
  'getGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
  'getMessagesWith' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(DMMessage)],
      ['query'],
    ),
  'getShopItems' : IDL.Func([], [IDL.Vec(ShopItem)], ['query']),
  'getUserHarem' : IDL.Func([IDL.Principal], [IDL.Vec(OwnedWaifu)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWaifuCharacters' : IDL.Func([], [IDL.Vec(WaifuCharacter)], ['query']),
  'huntWaifuInGroup' : IDL.Func([IDL.Text], [IDL.Opt(WaifuCharacter)], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinGroup' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendDM' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'sendFriendRequest' : IDL.Func([IDL.Principal], [], []),
  'sendGroupMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'transferOnex' : IDL.Func([IDL.Principal, IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ShopItem = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'itemType' : IDL.Text,
    'price' : IDL.Nat,
  });
  const WaifuCharacter = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'series' : IDL.Text,
    'imageUrl' : IDL.Text,
    'rarity' : IDL.Text,
  });
  const OwnedWaifu = IDL.Record({
    'userId' : IDL.Principal,
    'obtainedAt' : IDL.Nat,
    'isFavorite' : IDL.Bool,
    'characterId' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Group = IDL.Record({
    'members' : IDL.Vec(IDL.Principal),
    'name' : IDL.Text,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'spawnInterval' : IDL.Nat,
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'balance' : IDL.Nat,
    'displayName' : IDL.Text,
    'joinDate' : Time,
    'profilePic' : ExternalBlob,
  });
  const FriendRequest = IDL.Record({
    'status' : IDL.Text,
    'toUser' : IDL.Principal,
    'fromUser' : IDL.Principal,
  });
  const GroupMessage = IDL.Record({
    'id' : IDL.Text,
    'isWaifuSpawn' : IDL.Bool,
    'content' : IDL.Text,
    'waifuCharacterId' : IDL.Text,
    'senderPrincipal' : IDL.Principal,
    'timestamp' : Time,
    'senderName' : IDL.Text,
    'groupName' : IDL.Text,
  });
  const DMMessage = IDL.Record({
    'content' : IDL.Text,
    'toUser' : IDL.Principal,
    'timestamp' : Time,
    'fromUser' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptFriendRequest' : IDL.Func([IDL.Principal], [], []),
    'addMemberToGroup' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'addShopItem' : IDL.Func([ShopItem], [], []),
    'addWaifuCharacter' : IDL.Func([WaifuCharacter], [], []),
    'addWaifuToHarem' : IDL.Func([OwnedWaifu], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGroup' : IDL.Func([Group], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFriendRequests' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(FriendRequest)],
        ['query'],
      ),
    'getGroupMembers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getGroupMessages' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(GroupMessage)],
        ['query'],
      ),
    'getGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
    'getMessagesWith' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(DMMessage)],
        ['query'],
      ),
    'getShopItems' : IDL.Func([], [IDL.Vec(ShopItem)], ['query']),
    'getUserHarem' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(OwnedWaifu)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWaifuCharacters' : IDL.Func([], [IDL.Vec(WaifuCharacter)], ['query']),
    'huntWaifuInGroup' : IDL.Func([IDL.Text], [IDL.Opt(WaifuCharacter)], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinGroup' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendDM' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'sendFriendRequest' : IDL.Func([IDL.Principal], [], []),
    'sendGroupMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'transferOnex' : IDL.Func([IDL.Principal, IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };